### ISSUE TITLE
Is logstash for searching?

### ISSUE THREAD

**Issue by guettli** [elasticsearch/logstash#2602]
From the logstash page:

{{{
Speaking of searching, logstash comes with a web interface for searching and drilling into all of your logs.
}}}

I think this is misleading. New users think logstash is a storage and search server for logs. But AFAIK it is not.

I watched the youtube video of the start page, and now I know that you need some kind of storage for your logs.

Logstash is like a cool unix pipe for logs.

 Please review these first lines of your homepage.

Thank you for listening :-)

**Comment by purbon** [comment]
Hi,  
  I guess this refer to the point of using an UI (like kibana, that use to be integrated with logstash) to search and analyze your log stream.

If you fire this command (https://github.com/elasticsearch/logstash/blob/master/bin/logstash-web), from the console, you will be able to search your logs within ES by using kibana.

How would you rephrase it in order not to be misleading?

**Comment by guettli** [comment]
I refere to this page: http://logstash.net/

{{{
logstash

logstash is a tool for managing events and logs. You can use it to collect logs, parse them, and store them for later use (like, for searching). Speaking of searching, logstash comes with a web interface for searching and drilling into all of your logs.
}}}

You could write
{{{
...... comes with a web interface for searching and drilling into all of your logs in elasticsearch.
}}}

**Comment by untergeek** [comment]
This issue is resolved by the changes in documentation going forward in 1.5:

http://www.elasticsearch.org/guide/en/logstash/current/index.html

Note the absence of any references directly to Kibana or Logstash Web.  This is because the documentation is on the same site (elasticsearch.org/guide) that the Kibana documentation is on.

**Comment by purbon** [comment]
I guess with the comments of @untergeek we can close this issue. Please @guettli let me know if there are still issues with the new documentation and I open this thread again ;-)

/cheers

- purbon

**Comment by guettli** [comment]
Sorry, not resolved for me.

The current home page http://logstash.net/ states at the top:

logstash is a tool for managing events and logs. You can use it to collect logs, parse them, and store them for later use (like, for searching). Speaking of searching, logstash comes with a web interface for searching and drilling into all of your logs.

Please explain where the web interface for searching comes from.

I looked at this: http://www.elastic.co/guide/en/logstash/current/index.html

I see only docs about forwarding and filtering logs.

**Comment by jordansissel** [comment]
> logstash comes with a web interface

Logstash has `bin/logstash web` which is this web interface. It is Kibana 3.

I will agree that the text on that page may need updating once Logstash 1.5.0 is released (which no longer ships the 'logstash web' kibana launcher)
